
CREATE DATABASE StudentManagement;


USE StudentManagement;


CREATE TABLE COURSES (
    COURSE_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(500)
);


CREATE TABLE GROUPS (
    GROUP_ID INT PRIMARY KEY IDENTITY(1,1),
    COURSE_ID INT NOT NULL,
    NAME NVARCHAR(50) NOT NULL,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);


CREATE TABLE STUDENTS (
    STUDENT_ID INT PRIMARY KEY IDENTITY(1,1),
    GROUP_ID INT NOT NULL,
    FIRST_NAME NVARCHAR(50) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);
