USE StudentManagement;


SELECT 
    g.GROUP_ID,
    g.NAME as GROUP_NAME,
    c.NAME as COURSE_NAME,
    COUNT(s.STUDENT_ID) as STUDENT_COUNT
FROM GROUPS g
INNER JOIN COURSES c ON g.COURSE_ID = c.COURSE_ID
LEFT JOIN STUDENTS s ON g.GROUP_ID = s.GROUP_ID
GROUP BY g.GROUP_ID, g.NAME, c.NAME
HAVING COUNT(s.STUDENT_ID) < 10;
