USE StudentManagement;


SELECT 
    c.NAME as COURSE_NAME,
    g.NAME as GROUP_NAME,
    s.FIRST_NAME,
    s.LAST_NAME,
    s.STUDENT_ID
FROM COURSES c
INNER JOIN GROUPS g ON c.COURSE_ID = g.COURSE_ID
INNER JOIN STUDENTS s ON g.GROUP_ID = s.GROUP_ID
ORDER BY c.NAME, g.NAME, s.LAST_NAME, s.FIRST_NAME;
